export const fakePromo = [
    {
      id: 1,
      name: 'Ma Promo',
      date: '21/08/2000',
      message: 'Blablablalbla',
      code_promo: '2388ABBB',
    },
    {
      id: 2,
      name: 'Ma Promo1',
      date: '21/08/2000',
      message: 'Blablablalbla',
      code_promo: '2388ABBB',
    },
    {
      id: 3,
      name: 'Ma Promo2',
      date: '21/08/2000',
      message: 'Blablablalbla',
      code_promo: '2388ABBB',
    },
    {
      id: 4,
      name: 'Ma Promo4',
      date: '21/08/2000',
      message: 'Blablablalbla',
      code_promo: '2388ABBB',
    },
    {
      id: 5,
      name: 'Ma Promo4',
      date: '21/08/2000',
      message: 'Blablablalbla',
      code_promo: '2388ABBB',
    },
    {
      id: 6,
      name: 'Ma Promo4',
      date: '21/08/2000',
      message: 'Blablablalbla',
      code_promo: '2388ABBB',
    },
    {
      id: 7,
      name: 'Ma Promo4',
      date: '21/08/2000',
      message: 'Blablablalbla',
      code_promo: '2388ABBB',
    },
    {
      id: 8,
      name: 'Ma Promo4',
      date: '21/08/2000',
      message: 'Blablablalbla',
      code_promo: '2388ABBB',
    },
    {
      id: 9,
      name: 'Ma Promo4',
      date: '21/08/2000',
      message: 'Blablablalbla',
      code_promo: '2388ABBB',
    },
    {
      id: 10,
      name: 'Ma Promo4',
      date: '21/08/2000',
      message: 'Blablablalbla',
      code_promo: '2388ABBB',
    },
  ];